name: Khulnasoft Integration Tests
on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

# By specifying the access of one of the scopes, all of those that are not specified are set to 'none'.
permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # To allow writing PR comments and setting emojis
  pull-requests: write

env:
  # renovate: datasource=github-releases depName=kubernetes-sigs/kind
  KIND_VERSION: v0.27.0
  KHULNASOFT_REPO_OWNER: khulnasoft
  KHULNASOFT_REPO_REF: main
  KHULNASOFT_CLI_REF: latest
  CURL_PARALLEL: ${{ vars.CURL_PARALLEL || 10 }}

jobs:
  khulnasoft-connectivity-tests:
    timeout-minutes: 360
    name: Khulnasoft Connectivity Tests
    if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Prepare variables for pushes to main
        if: github.event_name == 'push'
        run: |
          echo "PROXY_IMAGE=quay.io/khulnasoft/khulnasoft-envoy" >> $GITHUB_ENV
          echo "PROXY_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "PROXY_GITHUB_REPO=github.com/khulnasoft/proxy" >> $GITHUB_ENV

      - name: Prepare variables for PR
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        run: |
          echo "PROXY_IMAGE=quay.io/khulnasoft/khulnasoft-envoy-dev" >> $GITHUB_ENV
          echo "PROXY_TAG=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "PROXY_GITHUB_REPO=github.com/${{github.event.pull_request.head.repo.full_name}}" >> $GITHUB_ENV

      - name: Checkout Khulnasoft ${{ env.KHULNASOFT_REPO_REF }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ env.KHULNASOFT_REPO_OWNER }}/khulnasoft # Be aware that this is the Khulnasoft repository and not the one of the proxy itself!
          ref: ${{ env.KHULNASOFT_REPO_REF }}
          persist-credentials: false

      - name: Extracting Khulnasoft version
        run: |
          echo "KHULNASOFT_IMAGE_TAG=v$(cat ./VERSION)" >> $GITHUB_ENV

      - name: Install Khulnasoft CLI ${{ env.KHULNASOFT_CLI_REF }}
        run: |
          versionPattern="^v[0-9]+\.[0-9]+\.[0-9]+$"
          if [[ ${{ env.KHULNASOFT_CLI_REF }} =~ $versionPattern ]]; then
            curl -sSL --remote-name-all https://github.com/khulnasoft/khulnasoft-cli/releases/download/${{ env.KHULNASOFT_CLI_REF }}/khulnasoft-linux-amd64.tar.gz{,.sha256sum}
            sha256sum --check khulnasoft-linux-amd64.tar.gz.sha256sum
            sudo tar xzvfC khulnasoft-linux-amd64.tar.gz /usr/local/bin
            rm khulnasoft-linux-amd64.tar.gz{,.sha256sum}
          else
            cid=$(docker create quay.io/khulnasoft/khulnasoft-cli-ci:${{ env.KHULNASOFT_CLI_REF }} ls)
            sudo docker cp $cid:/usr/local/bin/khulnasoft /usr/local/bin
            docker rm $cid
          fi
          khulnasoft version

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          version: ${{ env.KIND_VERSION }}
          config: '.github/kind-config.yaml'
          cluster_name: 'kind'

      - name: Patch Khulnasoft Agent Dockerfile
        shell: bash
        run: |
          sed -i -E 's|(ARG KHULNASOFT_ENVOY_IMAGE=)(quay\.io\/khulnasoft\/khulnasoft-envoy:)(.*)(@sha256:[0-9a-z]*)|\1${{ env.PROXY_IMAGE }}:${{ env.PROXY_TAG }}|' ./images/khulnasoft/Dockerfile
          cat ./images/khulnasoft/Dockerfile
          if git diff --exit-code ./images/khulnasoft/Dockerfile; then
            echo "Dockerfile not modified"
            exit 1
          fi

      - name: Install Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: 1.23.7

      - name: Redirect proxy module
        shell: bash
        if: env.PROXY_GITHUB_REPO != 'github.com/khulnasoft/proxy'
        run: echo "replace github.com/khulnasoft/proxy => ${{ env.PROXY_GITHUB_REPO }} ${{ env.PROXY_TAG }}" >> go.mod

      - name: Update proxy module
        shell: bash
        if: env.PROXY_GITHUB_REPO == 'github.com/khulnasoft/proxy'
        run: go get ${{ env.PROXY_GITHUB_REPO }}@${{ env.PROXY_TAG }}

      - name: Vendor proxy module
        shell: bash
        run: |
          go mod tidy && \
          go mod verify && \
          go mod vendor

      - name: Wait for Khulnasoft Proxy image to be available
        timeout-minutes: 45
        shell: bash
        run: until docker manifest inspect ${{ env.PROXY_IMAGE }}:${{ env.PROXY_TAG }} &> /dev/null; do sleep 15s; done

      - name: Build Khulnasoft Agent & Operator with patched Khulnasoft Proxy Image
        shell: bash
        run: DOCKER_IMAGE_TAG=${{ env.KHULNASOFT_IMAGE_TAG }} make docker-khulnasoft-image docker-operator-generic-image

      - name: Load Khulnasoft Images into kind
        shell: bash
        run: |
          kind load docker-image \
            --name kind \
            quay.io/khulnasoft/operator-generic:${{ env.KHULNASOFT_IMAGE_TAG }} \
            quay.io/khulnasoft/khulnasoft:${{ env.KHULNASOFT_IMAGE_TAG }}

      - name: Install Khulnasoft
        timeout-minutes: 10
        shell: bash
        run: |
          khulnasoft install \
            --chart-directory install/kubernetes/khulnasoft \
            --helm-set bpf.monitorAggregation=none \
            --helm-set loadBalancer.l7.backend=envoy \
            --helm-set=tls.readSecretsOnlyFromSecretsNamespace=true \
            --helm-set=tls.secretSync.enabled=true \
            --helm-set image.repository=quay.io/khulnasoft/khulnasoft \
            --helm-set image.tag=${{ env.KHULNASOFT_IMAGE_TAG }} \
            --helm-set image.useDigest=false \
            --helm-set image.pullPolicy=Never \
            --helm-set operator.image.repository=quay.io/khulnasoft/operator \
            --helm-set operator.image.suffix= \
            --helm-set operator.image.tag=${{ env.KHULNASOFT_IMAGE_TAG }} \
            --helm-set operator.image.useDigest=false \
            --helm-set operator.image.pullPolicy=Never \
            --helm-set envoy.enabled=false \
            --helm-set debug.enabled=true \
            --helm-set debug.verbose=envoy

          khulnasoft hubble enable
          khulnasoft status --wait
          khulnasoft hubble port-forward&

      - name: Execute Khulnasoft L7 Connectivity Tests
        shell: bash
        run: khulnasoft connectivity test --test="l7|sni|tls|ingress|check-log-errors" --curl-parallel=${{ env.CURL_PARALLEL }} --collect-sysdump-on-failure --flush-ct --sysdump-hubble-flows-count=100000 --sysdump-hubble-flows-timeout=15s

      - name: Gather Khulnasoft system dump
        if: failure()
        shell: bash
        run: khulnasoft sysdump --output-filename khulnasoft-sysdump-final


      - name: Upload Khulnasoft system dump
        if: failure()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: khulnasoft-integration-test-sysdumps
          path: khulnasoft-sysdump-*.zip
          retention-days: 5
